/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f8f3e6',
        'primary-fixed-dim': '#afcebd',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#9ed2b0',
        'surface-dim': '#dedacd',
        'on-surface-variant': '#424844',
        surface: '#fef9ec',
        'on-tertiary-fixed-variant': '#1e5036',
        'on-background': '#1d1c14',
        'secondary-fixed': '#ffddb4',
        'secondary-container': '#fec575',
        'surface-bright': '#fef9ec',
        'on-primary': '#ffffff',
        'primary-fixed': '#cbead8',
        'surface-variant': '#e7e2d5',
        'tertiary-container': '#063d25',
        background: '#fef9ec',
        'on-secondary-fixed-variant': '#633f00',
        'outline-variant': '#c2c8c2',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#042016',
        primary: '#082419',
        'surface-container-high': '#ede8db',
        'inverse-surface': '#323028',
        'error-container': '#ffdad6',
        'on-surface': '#1d1c14',
        'on-secondary-container': '#794f06',
        'inverse-primary': '#afcebd',
        'primary-container': '#1f3a2e',
        secondary: '#80560e',
        tertiary: '#002514',
        'on-tertiary-container': '#76a889',
        'surface-container': '#f3eee1',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#002111',
        'on-primary-fixed-variant': '#314c40',
        'on-error-container': '#93000a',
        outline: '#727974',
        'on-secondary-fixed': '#291800',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#f5bc6e',
        'surface-container-highest': '#e7e2d5',
        'on-tertiary': '#ffffff',
        'surface-tint': '#486457',
        'tertiary-fixed': '#b9efcb',
        'on-primary-container': '#86a494',
        'inverse-on-surface': '#f5f0e3',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-lg': '1.5rem',
        'space-xs': '0.25rem',
        gutter: '1rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-xl': '2rem',
        margin: '1.25rem',
      },
      fontFamily: {
        'headline-xl': ['Nunito Sans', 'sans-serif'],
        'numeric-sub': ['Nunito Sans', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-lg': ['Nunito Sans', 'sans-serif'],
        'body-md': ['Nunito Sans', 'sans-serif'],
        'headline-xl-mobile': ['Nunito Sans', 'sans-serif'],
        'headline-md': ['Nunito Sans', 'sans-serif'],
        'numeric-hero-mobile': ['Nunito Sans', 'sans-serif'],
        'body-xl': ['Nunito Sans', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'numeric-hero': ['Nunito Sans', 'sans-serif'],
        'headline-lg': ['Nunito Sans', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        sans: ['Nunito Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'numeric-sub': ['20px', { lineHeight: '26px', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'numeric-hero-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-xl': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'numeric-hero': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg': ['26px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
      },
      maxWidth: {
        xl: '640px',
      },
    },
  },
  plugins: [],
}
